application: factionized
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: media/css

- url: /js
  static_dir: media/js

- url: /images
  static_dir: media/images

- url: /tasks.*
  login: admin
  script: main.py 

- url: .*
  script: main.py
